homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  
map:
sun:
alexa:
config:
updater:
  include_used_components: true

notify:
  - name: Facebook Notifications
    platform: facebook
    page_access_token: !secret fb_page_access_token

google_assistant:
  project_id: !secret google_assistant_project
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key

cloud:
  alexa:
    filter:
      exclude_domains:
        - automation
        - sensor
        - group
        - media_player

facebook_webhook:
  verify_token: !secret fb_verify_token
  access_token: !secret fb_page_access_token
  allowed_ids: !include secret/trusted_facebook_ids.yaml

xiaomi_aqara:
  interface: !secret iot_interface
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key
      mac: !secret xiaomi_mac
      host: !secret xiaomi_ip

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: homeassistant/alarm
    command_topic: homeassistant/alarm/set
    code: !secret alarm_control_code
    pending_time: 30
    delay_time: 20
    trigger_time: 60
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

keyboard_remote:
  device_name: 'Remote control'
  type: 'key_down'

tts:
  - platform: google
  - platform: picotts

python_script:

logbook: !include config/logbook.yaml
recorder: !include config/recorder.yaml
history: !include config/history.yaml
panel_custom: !include config/panel_custom.yaml

http: !include config/http.yaml
frontend: !include config/frontend.yaml

mqtt: !include config/mqtt.yaml
mqtt_statestream: !include config/mqtt_statestream.yaml


light: !include_dir_merge_list light
switch: !include_dir_merge_list switch
device_tracker: !include_dir_merge_list device_tracker
media_player: !include_dir_merge_list media_player
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
automation: !include_dir_merge_list automation
input_select: !include_dir_merge_list input/select
input_boolean: !include_dir_merge_list input/boolean
scene: !include_dir_merge_list scene
script: !include_dir_merge_list script
group: !include_dir_merge_named group
zone: 
  !include_dir_merge_list zones

intent_script: !include config/intent_script.yaml
conversation:
  intents: !include config/conversation_intent.yaml

