homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  
#logger:
#  default: info

#lirc:
map:
sun:
alexa:
config:
updater:

logbook: !include logbook.yaml
recorder: !include recorder.yaml

history: !include config/history.yaml
http: !include config/http.yaml
frontend: !include config/frontend.yaml
mqtt: !include config/mqtt.yaml
mqtt_statestream: !include config/mqtt_statestream.yaml

#zwave:
#  usb_path: /dev/ttyUSB0

notify:
  - name: Facebook Notifications
    platform: facebook
    page_access_token: !secret fb_page_access_token

google_assistant:
  project_id: !secret google_assistant_project
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key

cloud:
  alexa:
    filter:
      exclude_domains:
        - automation
        - sensor
        - group
        - media_player

facebook_webhook:
  verify_token: !secret fb_verify_token
  access_token: !secret fb_page_access_token
  allowed_ids: !include secret/trusted_facebook_ids.yaml

xiaomi_aqara:
  interface: !secret iot_interface
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key
      mac: !secret xiaomi_mac
      host: !secret xiaomi_ip

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: homeassistant/alarm
    command_topic: homeassistant/alarm/set
    code: !secret alarm_control_code
    pending_time: 30
    delay_time: 20
    trigger_time: 60
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0


keyboard_remote:
  device_name: 'Remote control'
  type: 'key_down'

tts:
  - platform: google
  - platform: picotts

python_script:
device_tracker: !include device_tracker.yaml
scene: !include scene.yaml
intent_script: !include intent_script.yaml
media_player: !include media_player.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
light: !include light.yaml
automation: !include automations.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
script: !include scripts.yaml
panel_custom: !include panel_custom.yaml

group: !include_dir_merge_named groups/

zone: 
  !include_dir_merge_list zones

conversation:
  intents: !include conversation_intent.yaml

