
homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

history:
logbook:
  exclude:
    entities:
      - binary_sensor.motion_sensor_158d000120cce2
      - sensor.illumination_286c07f0a0c6
      - sensor.geoscience_australia
      - sensor.usgs_all_earthquakes
     
map:
sun:

recorder: !include recorder.yaml

google_assistant:
  project_id: !secret google_assistant_project
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  agent_user_id: !secret google_assistant_agent_user_id
  api_key: !secret google_assistant_api_key

cloud:
alexa:

#zwave:
#  usb_path: /dev/ttyUSB0

notify:
#  - name: Push Notifications
#    platform: html5
#    gcm_api_key: !secret gcm_api_key
#    gcm_sender_id: !secret gcm_sender_id
  - name: Facebook Notifications
    platform: facebook
    page_access_token: !secret fb_page_access_token

facebook_webhook:
  verify_token: !secret fb_verify_token
  access_token: !secret fb_page_access_token
  allowed_ids: !include secret/trusted_facebook_ids.yaml

#duckdns:
#  domain: !secret domain
#  access_token: !secret duck_access_token

config:

influxdb:
  host: !secret mqtt_broker_host
  database: homeassistant
  default_measurement: state

http:
  api_password: !secret api_password
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  trusted_networks: !include secret/trusted_networks.yaml
  ip_ban_enabled: True
  login_attempts_threshold: 5

frontend:
#  extra_html_url:
#    - /home/homeassistant/.homeassistant/www/custom_ui/state-card-floorplan.html
  javascript_version: latest
  themes:
    day:
      primary_color: orange
    night:
      primary_color: black


updater:

scene: !include scene.yaml
intent_script: !include intent_script.yaml

conversation:
  intents: !include conversation_intent.yaml

mqtt:
  broker: !secret mqtt_broker_host
  discovery: true
  discovery_prefix: homeassistant

xiaomi_aqara:
  interface: !secret iot_interface
  discovery_retry: 3
  gateways:
    - mac: !secret xiaomi_mac
      host: !secret xiaomi_ip
      key: !secret xiaomi_key

alarm_control_panel:
  - platform: manual_mqtt
    state_topic: homeassistant/alarm
    command_topic: homeassistant/alarm/set
    code: !secret alarm_control_code
    pending_time: 1
    delay_time: 1
    trigger_time: 60

lirc:

keyboard_remote:
  device_name: 'Remote control'
  type: 'key_down'

tts:
  - platform: google

device_tracker:
  - platform: gpslogger
    max_gps_accuracy: 20

  - platform: ping
    hosts: !include secret/ping_hosts.yaml

  - platform: bluetooth_tracker

# - platform: bluetooth_le_tracker

media_player: !include media_player.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
light: !include light.yaml
automation: !include automations.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
group: !include groups.yaml
script: !include scripts.yaml
panel_custom: !include panel_custom.yaml

zone: 
  !include_dir_merge_list zones
        
python_script:

