
- platform: tplink
  host: !secret tp_lb_kitchen_daylight_ip
  name: Kitchen Light

- platform: tplink
  host: !secret tp_lb_hallway_ip
  name: Hallway Light

- platform: yeelight
  devices:

    !secret yee_dining_ip:
      name: Dining Light
      transition: 2000

    !secret yee_kitchen_ip:
      name: Bathroom Light
      transition: 2000

    !secret yee_lounge_ip:
      name: Lounge Light
      transition: 2000

    !secret yee_lounge_extra_ip:
      name: Lounge Light Extra
      transition: 2000

- platform: group
  name: House Lights
  entities:
    - light.dining_light
    - light.hallway_light
    - light.bathroom_light
    - light.kitchen_light
    - light.gateway_light_286c07f0a0c6

- platform: group
  name: Living Room Lights
  entities:
    - light.lounge_light
    - light.lounge_light_extra
    
# Good white
#
#brightness: 255
#color_temp: 295
#min_mireds: 153
#max_mireds: 588
#rgb_color: 255,189.32800441054707,134.5356812411473
#xy_color: 0.454,0.387
#effect_list: Disco,Slow Temp,Strobe epilepsy!,Strobe color,Alarm,Police,Police2,Christmas,RGB,Random Loop,Fast Random Loop,Slowdown,WhatsApp,Facebook,Twitter,Stop
#friendly_name: Bathroom Light
#supported_features: 127
#
