---
#- platform: yr
#  name: Forecast
#  forecast: 24
#  monitored_conditions:
#    - temperature
#    - symbol
#    - precipitation
##    - windSpeed
#    - pressure
##    - windDirection
#    - humidity
#    - fog
#    - cloudiness
##    - lowClouds
##    - mediumClouds
##    - highClouds
##    - dewpointTemperature

- platform: bom
  station: IDN60901.94767
  name: Sydney
  monitored_conditions:
    - apparent_t
    - cloud
    - cloud_type
    - gust_kmh
    - air_temp
    - press
    - rain_trace
    - rel_hum
    - weather
    - wind_spd_kmh

- platform: wunderground
  api_key: !secret wunderground_key
  monitored_conditions: 
    - alerts
    - feelslike_c
    - heat_index_c
    - solarradiation
    - temp_c
    - UV
    - weather_1h
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n

- platform: moon

- platform: broadlink
  host: !secret ir_blaster_ip
  mac: !secret ir_blaster_mac
  update_interval: 60
  monitored_conditions:
    - temperature

- platform: command_line
  name: CPU Temperature
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '째C'
  value_template: '{{ value | multiply(0.001) }}'

- platform: cpuspeed

- platform: cert_expiry
  host: catslair39.duckdns.org
  name: CatsLair SSL Expiry

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: systemmonitor
  resources:
    - type: memory_free
    - type: memory_use
    - type: swap_free
    - type: swap_use
    - type: load_1m
    - type: load_5m
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /mnt/media-a
    - type: disk_use_percent
      arg: /mnt/media-b

- platform: time_date
  display_options:
    - date
    - time
    - time_utc
    - beat

- platform: mqtt
  #state_topic: 'display/kitchen/sensor/temperature_3ffc9f74/state'
  state_topic: 'display/kitchen/sensor/temperature_3ffcaf94/state'
  name: Display Temperature
  unit_of_measurement: '째C'

- platform: mqtt
  state_topic: 'display/aquarium/sensor/temperature_28FF5DFFA1170464/state'
  name: Aquarium Temperature
  unit_of_measurement: '째C'


- platform: mqtt
  state_topic: 'display/aquarium/sensor/temperature_bme/state'
  name: Lounge Temperature
  unit_of_measurement: '째C'

- platform: mqtt
  state_topic: 'display/aquarium/sensor/pressure_bme/state'
  name: Lounge Barometric
  unit_of_measurement: 'hPa'

- platform: statistics
  name: Aquarium Temperature Stats
  entity_id: sensor.aquarium_temperature
  max_age: 24:00

- platform: new_georss_events
  name: NSW RFS Major Incidents
  url: 'http://www.rfs.nsw.gov.au/feeds/majorIncidents.xml'
  unit_of_measurement: 'Incidents'
  radius: 100
  publish_events: true
  sort_by: 'date_published'
  categories:
    - 'Emergency Warning'
    - 'Watch and Act'
    - 'Advice'

- platform: new_georss_events
  name: USGS All Earthquakes
  url: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.atom'
  radius: 300000    
  publish_events: true
  sort_by: 'date_published'
  unit_of_measurement: 'Earthquakes'
  categories:
    - 'Past Hour'
    - 'Past Day'
  custom_attributes:
    - name: magnitude
      source: title
      regexp: '^M (?P<custom_attribute>\d+.\d+) -.*'
    - name: distfrom
      source: title
      regexp: '^M \d+\.\d+ - (?P<custom_attribute>\d+)km.*'
    - name: direction 
      source: title
      regexp: '^M \d+\.\d+ - \d+km (?P<custom_attribute>.*) of .*'
    - name: location 
      source: title
      regexp: '^M \d+\.\d+ - .* of (?P<custom_attribute>.*)'

- platform: new_georss_events
  name: BGS Worlwide Earthquakes
  url: 'http://www.bgs.ac.uk/feeds/worldSeismology.xml'
  sort_by: 'date_published'
  unit_of_measurement: 'Earthquakes'
  radius: 300000
  categories:
    - 'EQMH'
  custom_attributes:
    - name: magnitude
      source: title
      regexp: 'World Earthquake alert: M (?P<custom_attribute>\d+.\d+):.*'

- platform: new_georss_events
  name: Geoscience Australia
  url: 'http://www.ga.gov.au/earthquakes/all_recent.rss'
  sort_by: 'date_published'
  unit_of_measurement: 'Earthquakes'
  radius: 3000
  publish_events: true
  custom_attributes:
    - name: magnitude
      source: title
      regexp: '^Magnitude (?P<custom_attribute>\d+.\d+), .*'


- platform: internode
  username: test
  password: test
  service: 123456
  monitored_variables:
    - usage
    
