
- platform: broadlink
  type: rm2
  host: !secret broadlink_rm2_ip
  mac: !secret broadlink_rm2_mac
  friendly_name: Lounge IR
  switches:
    audio:
      friendly_name: Audio
      command_on: JgDYAAABGIgUMhMPFDIUDhMPEzMTDxMzEw8UMhMPFDEUMhMPFDITDxQPEzIUDhMQEzIUDxMPEw8UMhQPEzIUMRQPEzIUMhMyFQADOAABGIgUMhMPFDIUDhQPEzIUDhQyEw8UMhMPFDITMhQOFDITDxQPEzIUDxMPFDITDxMPEw8UMhQPEzIUMhMPFDEUMhMyFAADOQABF4oUMRMPFDITDxQPEzIUDxMyExATMhMPFDIUMRQPEzITDxQPEzIUDxMPFDITDxQPEw8UMRMPFDIUMhMPFDITMhMyFAANBQ==
      command_off: JgDYAAABGIgUMhMPFDIUDhMPEzMTDxMzEw8UMhMPFDEUMhMPFDITDxQPEzIUDhMQEzIUDxMPEw8UMhQPEzIUMRQPEzIUMhMyFQADOAABGIgUMhMPFDIUDhQPEzIUDhQyEw8UMhMPFDITMhQOFDITDxQPEzIUDxMPFDITDxMPEw8UMhQPEzIUMhMPFDEUMhMyFAADOQABF4oUMRMPFDITDxQPEzIUDxMyExATMhMPFDIUMRQPEzITDxQPEzIUDxMPFDITDxQPEw8UMRMPFDIUMhMPFDITMhMyFAANBQ==
    tv_soniq:
      friendly_name: TV
      command_on: JgBYAAABKZMSEhE3ExIRExE3EzYSNxISEzYSEhI2EzYTNhISEjYTNhMSEjYTNhI2ExIRExISEhITNhETExETEhI2EzYSNhM2EgAE6wABKUoUAAxIAAEqSBEADQU=
      command_off: JgBYAAABKZMSEhE3ExIRExE3EzYSNxISEzYSEhI2EzYTNhISEjYTNhMSEjYTNhI2ExIRExISEhITNhETExETEhI2EzYSNhM2EgAE6wABKUoUAAxIAAEqSBEADQU=
    av_pioneer:
      friendly_name: Pioneer
      command_on: JgCQAAABGYkUMRUPFDEVDxQPFDIUDxQyFA8UMRUPFDEVMRQQFDEUEBQPFA8UMhQxFDIUEBMQFA8UMRUxExEUDxQPEzMTMhQyEwADbAABGYgTMxMQEzMTEBMREzITERMyExETMhMREzITMxMQEzMTEBQPFBAUMRMzFDIUDxQPFBAUMRQyFA8UEBMQFDEUMhMzEwANBQAAAAAAAAAA=
      command_off: JgCQAAABGYkUMRUPFDEVDxQPFDIUDxQyFA8UMRUPFDEVMRQQFDEUEBQPFA8UMhQxFDIUEBMQFA8UMRUxExEUDxQPEzMTMhQyEwADbAABGYgTMxMQEzMTEBMREzITERMyExETMhMREzITMxMQEzMTEBQPFBAUMRMzFDIUDxQPFBAUMRQyFA8UEBMQFDEUMhMzEwANBQAAAAAAAAAA=
    stb_fetch:
      friendly_name: FetchTV
      command_on: JgBQAAABKJQTEhMSFDYTEhMSEzcUNhQSExISOBM2FBITEhMSEzcTEhM3ExITNxM3FDYTEhM3EhMTExI4ExISExMSEjgSExI4EwAFXwABKEoTAA0FAAAAAAAAAAA=
      command_off: JgBQAAABKJQTEhMSFDYTEhMSEzcUNhQSExISOBM2FBITEhMSEzcTEhM3ExITNxM3FDYTEhM3EhMTExI4ExISExMSEjgSExI4EwAFXwABKEoTAA0FAAAAAAAAAAA=

- platform: tplink
  name: Fish Lamp
  friendly_name: Fish Lamp
  host: !secret tplink_fish_switch_ip

- platform: broadlink
  type: 'spmini2'
  host: !secret sp3mini2_washing_ip
  mac: !secret sp3mini2_washing_mac
  friendly_name: Washing Machine

- platform: broadlink
  type: 'spmini2'
  host: !secret sp3mini2_fan_ip
  mac: !secret sp3mini2_fan_mac
  friendly_name: Fan

- platform: flux
  name: Flux Lights
  lights:
    - lights.hallway
    - lights.lounge_light_extra
    - lights.kitchen_light_daylight


