name: Cats Lair 
views: 
- name: main
  id: main
  title: Control
  icon: mdi:star
  cards: !include ui/main.yaml

- name: Weather
  title: Weather
  icon: mdi:cloud
  cards: !include ui/weather.yaml

- name: media
  id: view_media
  title: Media
  icon: mdi:play-network
  cards: !include ui/media.yaml

- name: snow
  id: view_SNOW
  TITLE: Snow
  icon: mdi:snowflake
  cards: !include ui/snow.yaml

- name: Status
  title: Status Report
  icon: mdi:speedometer
  cards: !include ui/status.yaml
