
#- platform: broadlink
#  type: 'spmini2'
#  host: !secret sp3mini2_fan_ip
#  mac: !secret sp3mini2_fan_mac
#  friendly_name: Fan

- platform: tplink
  name: Range
  friendly_name: Range
  host: !secret tplink_fish_switch_ip
