
- platform: broadlink
  type: rm2
  host: !secret broadlink_rm2_ip
  mac: !secret broadlink_rm2_mac
  friendly_name: Lounge IR
  switches:
    audio:
      friendly_name: Audio
      command_on: JgDYAAABGIgUMhMPFDIUDhMPEzMTDxMzEw8UMhMPFDEUMhMPFDITDxQPEzIUDhMQEzIUDxMPEw8UMhQPEzIUMRQPEzIUMhMyFQADOAABGIgUMhMPFDIUDhQPEzIUDhQyEw8UMhMPFDITMhQOFDITDxQPEzIUDxMPFDITDxMPEw8UMhQPEzIUMhMPFDEUMhMyFAADOQABF4oUMRMPFDITDxQPEzIUDxMyExATMhMPFDIUMRQPEzITDxQPEzIUDxMPFDITDxQPEw8UMRMPFDIUMhMPFDITMhMyFAANBQ==
      command_off: JgDYAAABGIgUMhMPFDIUDhMPEzMTDxMzEw8UMhMPFDEUMhMPFDITDxQPEzIUDhMQEzIUDxMPEw8UMhQPEzIUMRQPEzIUMhMyFQADOAABGIgUMhMPFDIUDhQPEzIUDhQyEw8UMhMPFDITMhQOFDITDxQPEzIUDxMPFDITDxMPEw8UMhQPEzIUMhMPFDEUMhMyFAADOQABF4oUMRMPFDITDxQPEzIUDxMyExATMhMPFDIUMRQPEzITDxQPEzIUDxMPFDITDxQPEw8UMRMPFDIUMhMPFDITMhMyFAANBQ==
    tv_soniq:
      friendly_name: TV
      command_on: JgBYAAABKZMSEhE3ExIRExE3EzYSNxISEzYSEhI2EzYTNhISEjYTNhMSEjYTNhI2ExIRExISEhITNhETExETEhI2EzYSNhM2EgAE6wABKUoUAAxIAAEqSBEADQU=
      command_off: JgBYAAABKZMSEhE3ExIRExE3EzYSNxISEzYSEhI2EzYTNhISEjYTNhMSEjYTNhI2ExIRExISEhITNhETExETEhI2EzYSNhM2EgAE6wABKUoUAAxIAAEqSBEADQU=
    av_pioneer:
      friendly_name: Pioneer
      command_on: JgCQAAABGYkUMRUPFDEVDxQPFDIUDxQyFA8UMRUPFDEVMRQQFDEUEBQPFA8UMhQxFDIUEBMQFA8UMRUxExEUDxQPEzMTMhQyEwADbAABGYgTMxMQEzMTEBMREzITERMyExETMhMREzITMxMQEzMTEBQPFBAUMRMzFDIUDxQPFBAUMRQyFA8UEBMQFDEUMhMzEwANBQAAAAAAAAAA=
      command_off: JgCQAAABGYkUMRUPFDEVDxQPFDIUDxQyFA8UMRUPFDEVMRQQFDEUEBQPFA8UMhQxFDIUEBMQFA8UMRUxExEUDxQPEzMTMhQyEwADbAABGYgTMxMQEzMTEBMREzITERMyExETMhMREzITMxMQEzMTEBQPFBAUMRMzFDIUDxQPFBAUMRQyFA8UEBMQFDEUMhMzEwANBQAAAAAAAAAA=
    stb_fetch:
      friendly_name: FetchTV
      command_on: JgBQAAABKJQTEhMSFDYTEhMSEzcUNhQSExISOBM2FBITEhMSEzcTEhM3ExITNxM3FDYTEhM3EhMTExI4ExISExMSEjgSExI4EwAFXwABKEoTAA0FAAAAAAAAAAA=
      command_off: JgBQAAABKJQTEhMSFDYTEhMSEzcUNhQSExISOBM2FBITEhMSEzcTEhM3ExITNxM3FDYTEhM3EhMTExI4ExISExMSEjgSExI4EwAFXwABKEoTAA0FAAAAAAAAAAA=

