exclude:
  domains:
    - yr
    - bom
    - wunderground
    - moon
    - group
    - weblink
    - updater
    - automation
    - scene
    - zone
  entities:
    - media_player.kitchen_speaker
    - input_boolean.awake
    - input_boolean.house_announcements
    - input_boolean.time_of_day_automation
    - input_select.tv_channel
    - input_select.tv_source
    - media_player.speaker
    - binary_sensor.switch_158d00019c9688
    - binary_sensor.switch_158d0001243e26
    - binary_sensor.switch_158d00019de7b4 
    - binary_sensor.cube_158d0001035c90
    - sun.sun
    - sensor.date
    - sensor.time       
    - sensor.time_utc
    - sensor.internet_time    
    - sensor.stardate
    - sensor.forecast_cloudiness
    - sensor.forecast_dewpoint_temperature
    - sensor.forecast_high_clouds
    - sensor.forecast_humidity
    - sensor.forecast_low_clouds
    - sensor.forecast_medium_clouds
    - sensor.forecast_precipitation
    - sensor.forecast_pressure
    - sensor.forecast_symbol
    - sensor.forecast_temperature
    - sensor.forecast_wind_direction
    - sensor.forecast_wind_speed
    - sensor.bom_sydney_air_temp_c
    - sensor.bom_sydney_cloud
    - sensor.bom_sydney_cloud_base
    - sensor.bom_sydney_cloud_oktas
    - sensor.bom_sydney_cloud_type 
    - sensor.bom_sydney_cloud_type_id
    - sensor.bom_sydney_delta_temp_c 
    - sensor.bom_sydney_dew_point_c 
    - sensor.bom_sydney_feels_like_c
    - sensor.bom_sydney_pressure_mb 
    - sensor.bom_sydney_pressure_msl
    - sensor.bom_sydney_pressure_qnh
    - sensor.bom_sydney_pressure_tend
    - sensor.bom_sydney_rain_today
    - sensor.bom_sydney_relative_humidity
    - sensor.bom_sydney_sea_state 
    - sensor.bom_sydney_swell_direction
    - sensor.bom_sydney_swell_height
    - sensor.bom_sydney_swell_period
    - sensor.bom_sydney_visability_km
    - sensor.bom_sydney_weather
    - sensor.bom_sydney_wind_direction
    - sensor.bom_sydney_wind_direction_kt
    - sensor.bom_sydney_wind_gust_kmh
    - sensor.bom_sydney_wind_gust_kt
    - sensor.bom_sydney_wind_speed_kmh
    - sensor.catslair_ssl_expiry


