# MPD via Socket
#
- platform: mpd_announce
  name: House Radio
  host: /run/mpd/socket
  force_queue: False

- platform: mpd_announce
  name: House Announcer
  host: /run/mpd-announce/socket
  force_queue: True
